/** HTML content attribute applicability, checked against the WHATWG index on 2026-09-08.
 * https://html.spec.whatwg.org/multipage/indices.html#attributes-3
 * Includes input capture, Remote Playback, Picture-in-Picture and CSS Shadow Parts extensions.
 * Type-only: no runtime attribute inventory is retained.
 */
export type HtmlAttributes = {
  abbr: { th: true };
  accept: { input: true };
  'accept-charset': { form: true };
  accesskey: { '*': true };
  action: { form: true };
  allow: { iframe: true };
  allowfullscreen: { iframe: true };
  alpha: { input: true };
  alt: { area: true; img: true; input: true };
  as: { link: true };
  async: { script: true };
  autocapitalize: { '*': true };
  autocomplete: { form: true; input: true; select: true; textarea: true };
  autocorrect: { '*': true };
  autofocus: { '*': true };
  autoplay: { audio: true; video: true };
  blocking: { link: true; script: true; style: true };
  capture: { input: true };
  charset: { meta: true };
  checked: { input: true };
  cite: { blockquote: true; del: true; ins: true; q: true };
  class: { '*': true };
  closedby: { dialog: true };
  color: { link: true };
  colorspace: { input: true };
  cols: { textarea: true };
  colspan: { td: true; th: true };
  command: { button: true };
  commandfor: { button: true };
  content: { meta: true };
  contenteditable: { '*': true };
  controls: { audio: true; video: true; img: true };
  coords: { area: true };
  crossorigin: { audio: true; img: true; link: true; script: true; video: true };
  data: { object: true };
  datetime: { del: true; ins: true; time: true };
  decoding: { img: true };
  default: { track: true };
  defer: { script: true };
  dir: { '*': true; bdo: true };
  dirname: { input: true; textarea: true };
  disabled: {
    button: true;
    input: true;
    optgroup: true;
    option: true;
    select: true;
    textarea: true;
    fieldset: true;
    link: true;
  };
  disablepictureinpicture: { video: true };
  disableremoteplayback: { audio: true; video: true };
  download: { a: true; area: true };
  draggable: { '*': true };
  enctype: { form: true };
  enterkeyhint: { '*': true };
  exportparts: { '*': true };
  fetchpriority: { img: true; link: true; script: true };
  for: { label: true; output: true; template: true };
  form: {
    button: true;
    fieldset: true;
    input: true;
    object: true;
    output: true;
    select: true;
    textarea: true;
  };
  formaction: { button: true; input: true };
  formenctype: { button: true; input: true };
  formmethod: { button: true; input: true };
  formnovalidate: { button: true; input: true };
  formtarget: { button: true; input: true };
  headers: { td: true; th: true };
  headingoffset: { '*': true };
  headingreset: { '*': true };
  height: {
    canvas: true;
    embed: true;
    iframe: true;
    img: true;
    input: true;
    object: true;
    source: true;
    picture: true;
    video: true;
  };
  hidden: { '*': true };
  high: { meter: true };
  href: { a: true; area: true; link: true; base: true };
  hreflang: { a: true; link: true };
  'http-equiv': { meta: true };
  id: { '*': true };
  imagesizes: { link: true };
  imagesrcset: { link: true };
  inert: { '*': true };
  inputmode: { '*': true };
  integrity: { link: true; script: true };
  is: { '*': true };
  ismap: { img: true };
  itemid: { '*': true };
  itemprop: { '*': true };
  itemref: { '*': true };
  itemscope: { '*': true };
  itemtype: { '*': true };
  kind: { track: true };
  label: { optgroup: true; option: true; track: true };
  lang: { '*': true };
  list: { input: true };
  loading: { iframe: true; img: true; audio: true; video: true };
  loop: { audio: true; video: true };
  low: { meter: true };
  max: { input: true; meter: true; progress: true };
  maxlength: { input: true; textarea: true };
  media: { link: true; meta: true; source: true; style: true };
  method: { form: true };
  min: { input: true; meter: true };
  minlength: { input: true; textarea: true };
  multiple: { input: true; select: true };
  muted: { audio: true; video: true };
  name: {
    button: true;
    fieldset: true;
    input: true;
    output: true;
    select: true;
    textarea: true;
    details: true;
    form: true;
    iframe: true;
    object: true;
    map: true;
    meta: true;
    slot: true;
  };
  nomodule: { script: true };
  nonce: { '*': true };
  novalidate: { form: true };
  open: { details: true; dialog: true };
  optimum: { meter: true };
  part: { '*': true };
  pattern: { input: true };
  ping: { a: true; area: true };
  placeholder: { input: true; textarea: true };
  playsinline: { video: true };
  popover: { '*': true };
  popovertarget: { button: true; input: true };
  popovertargetaction: { button: true; input: true };
  poster: { video: true };
  preload: { audio: true; video: true };
  readonly: { input: true; textarea: true };
  referrerpolicy: { a: true; area: true; iframe: true; img: true; link: true; script: true };
  rel: { a: true; area: true; link: true };
  required: { input: true; select: true; textarea: true };
  reversed: { ol: true };
  rows: { textarea: true };
  rowspan: { td: true; th: true };
  sandbox: { iframe: true };
  scope: { th: true };
  selected: { option: true };
  shadowrootclonable: { template: true };
  shadowrootcustomelementregistry: { template: true };
  shadowrootdelegatesfocus: { template: true };
  shadowrootmode: { template: true };
  shadowrootserializable: { template: true };
  shadowrootslotassignment: { template: true };
  shape: { area: true };
  size: { input: true; select: true };
  sizes: { link: true; img: true; source: true };
  slot: { '*': true };
  span: { col: true; colgroup: true };
  spellcheck: { '*': true };
  src: {
    audio: true;
    embed: true;
    iframe: true;
    img: true;
    input: true;
    script: true;
    source: true;
    video: true;
    track: true;
  };
  srcdoc: { iframe: true };
  srclang: { track: true };
  srcset: { img: true; source: true };
  start: { ol: true };
  step: { input: true };
  style: { '*': true };
  tabindex: { '*': true };
  target: { a: true; area: true; base: true; form: true };
  title: { '*': true; abbr: true; dfn: true; input: true; link: true; style: true };
  translate: { '*': true };
  type: {
    a: true;
    link: true;
    button: true;
    embed: true;
    object: true;
    source: true;
    input: true;
    ol: true;
    script: true;
  };
  usemap: { img: true };
  value: {
    button: true;
    option: true;
    data: true;
    input: true;
    li: true;
    meter: true;
    progress: true;
  };
  width: {
    canvas: true;
    embed: true;
    iframe: true;
    img: true;
    input: true;
    object: true;
    source: true;
    picture: true;
    video: true;
  };
  wrap: { textarea: true };
  writingsuggestions: { '*': true };
};
